import type { Metadata } from "next";
import { IBM_Plex_Serif, Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css"
import Header from "@/components/global/header";

const ibmPlexSerif = IBM_Plex_Serif({
  variable: "--font-ibm-plex-serif",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSerif.variable} ${ibmPlexSerif.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
